baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://blog.leighjohnson.me" # the base hostname & protocol for your site
title: "Psychonaut in Cyberspace"
brand: "/assets/logo-v3.png"
avatar: "https://avatars3.githubusercontent.com/u/2601819?v=3&s=200"

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

# https://github.com/pattex/jekyll-tagging
# Looks for _layouts/tag_page.html to generate _site/tag dir
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

gems:
  - jemoji
  - jekyll-haml
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      comments: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
